feat: Move Campers Modal
uwblueprint/focus-on-nature pull request #124
Opened 2022-10-05 22:08 UTC by uyxela

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-10-16 04:35 UTC, dhmi19 commented on backend/typescript/services/implementations/camperService.ts
> +    // let updatedCamperDTOs: Array<CamperDTO> = [];
Do we still need these comments? Can we delete for cleanup?

2022-10-16 04:36 UTC, dhmi19 commented on backend/typescript/services/implementations/camperService.ts
> +          earlyDropoff: camper.earlyDropoff.map((date) => date?.toString()),
Did you make these changes? There seem to be a bunch of changes that are not related to your ticket?

2022-10-22 14:30 UTC, Jasraj-Dhanoa requested changes
I tested out this feature with campID 63139c7bc3d7b55b44a01531

The functionality for Scenario 1 and Scenario 2 were working as expected. However, I was receiving an error when trying to test Scenario 3 (the alert didn't specify what specific error was occurring). It may be due to inconsistency within the database, but it will be great if you could take a look and test it out. Also, I've added some comments addressing the alert functionality and styling.

Please let me know if you have any questions.

2022-10-22 14:30 UTC, Jasraj-Dhanoa commented on frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx
> +  // Function to be called by the Move Campers Modal to update the campers
Alert alignment should be more refined. It tends to hide when scrolling up and overlaps the delete button. I noticed that the error alert was not showing any message whenever the camper could not be moved. Another way to make the interaction better would be to reduce the time it's displayed on the page. Also, is there a specific reason for choosing the alert compared to using a toast (which also provides the user the functionality to close it whenever they like)?

<img width="770" alt="Screen Shot 2022-10-21 at 10 22 47 PM" src="https://user-images.githubusercontent.com/50252969/197344242-22f3dce8-5ae6-40c5-99af-bdc128afb44c.png">
<img width="770" alt="Screen Shot 2022-10-21 at 10 34 24 PM" src="https://user-images.githubusercontent.com/50252969/197344246-803af1f9-f147-46db-804c-9b54585931b1.png">

2022-10-26 02:50 UTC, dhmi19 commented on backend/typescript/services/implementations/camperService.ts
> +    await session.startTransaction();
is this await necessary? I got a warning saying this is not necessary and the function documentation doesn't mention anything about Promises

2022-10-27 01:19 UTC, dhmi19 requested changes

2022-10-27 01:19 UTC, dhmi19 commented on frontend/src/components/pages/CampOverview/MoveCampersModal.tsx
> +                ) === 0
An admin can choose not to move any grouped campers so this condition is not accurate. I don't think the next button can ever be disabled for this page

2022-10-27 01:19 UTC, dhmi19 commented on frontend/src/components/pages/CampOverview/MoveCampersModal.tsx
> +                  <option key={campSessionsIdx} value={campSessionsItem.id}>
we need to "disable" the option if the camp session is the current session or a session in the past. We also need to disable the session if it doesn't have enough spots available. 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/57159970/198167258-3c22448b-b320-43d3-99fb-79b2522477d1.png">

2022-10-27 01:19 UTC, dhmi19 commented on frontend/src/components/pages/CampOverview/MoveCampersModal.tsx
> +                <Checkbox
Can you also remove the current selected camper from this list? eg: Tejas Test 1 should not be in this list

2022-10-27 01:19 UTC, dhmi19 commented on frontend/src/components/pages/CampOverview/CampersTable/CampersTable.tsx
> +  const [alertInfo, setAlertInfo] = React.useState<{
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/57159970/198168673-45ccde07-735a-4cb4-994c-ec012147f37a.png">
The toast should also disappear after 3 seconds and only take as much width as the text needs (or as specified by figma)

2022-11-12 18:13 UTC, dhmi19 requested changes
coming along well, just 2 final changes from my end I think. Sorry about the confusion with moving campers from the particular session :(

2022-11-12 18:13 UTC, dhmi19 commented on frontend/src/components/pages/CampOverview/MoveCamperModal/index.tsx
> +      CamperAPIClient.getCampersByChargeId(camper.chargeId).then(
Sorry about the confusion, this should be `getCampersByChargeIdAndSessionId`. We should only be able to move campers who were registered together and who are part of the current selected session. So you would pass in the current session id to the sessionID parameter.

2022-11-12 18:13 UTC, dhmi19 commented on frontend/src/components/pages/CampOverview/MoveCamperModal/PageTwo.tsx
> +                  campSessionsItem.id === camper.campSession ||
I think you missed a check here to disable all sessions which have an end date before today's date. IE: admin shouldn't be able to select a session in the past (session which has completed)

2023-01-25 18:19 UTC, twilkhoo commented
Completed here https://github.com/uwblueprint/focus-on-nature/pull/247.

2023-01-25 18:19 UTC, closed without merging