feat: add validation for non-negative EDLP amount
uwblueprint/focus-on-nature pull request #294
Opened 2023-08-02 00:25 UTC by thywang

## Notion ticket link

[Add validation to prevent negative amounts for EDLP during camp creation](https://www.notion.so/uwblueprintexecs/Add-validation-to-prevent-negative-amounts-for-EDLP-during-camp-creation-04780e5457824f33837c44ec2599f8f6?pvs=4)

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2023-08-17 01:41 UTC, williamtran10 requested changes
Fix lint error, otherwise LGTM

2023-08-17 03:15 UTC, thywang commented
Thanks! Have fixed the lint issue from this code change in the latest commit.

2023-08-17 03:18 UTC, williamtran10 approved these changes

2023-08-22 05:32 UTC, BraydenRoyston approved these changes
Great job!

2023-08-22 05:32 UTC, merged