feat: add formTemplate model and api
uwblueprint/focus-on-nature pull request #39
Opened 2022-03-30 04:04 UTC by uyousafzai54

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Tasks-38b49f83f6ce4b07ae188dabb37631e8?p=be8256776a614986a6d3df8f9b9fbabf)

## Implementation description
* Created a new Form Template model that contains an array of FormQuestion Object IDs.
* Created two new endpoints in the admin service for creating/updating and getting the Form Template

## Steps to test
1. Hit the following endpoint `http://localhost:5000/admin/formTemplate` with a POST request containing the following body below.
```
{
  "formQuestions": [
    {
      "question": "q1",
      "type": "Multiselect",
      "required": true,
      "description": "question description"
    },
    {
      "question": "q2",
      "type": "Multiselect",
      "required": false,
      "description": "question description",
      "options": [
        "'ayo'"
      ]
    }
  ]
}
```
2. Hit the following endpoint `http://localhost:5000/admin/formTemplate` with a GET request to get the resulting array. 

## What should reviewers focus on?
* API Implementation. 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-04-16 16:27 UTC, amanda-guo reviewed
Is there only supposed to be 1 formTemplate that can exist in the whole system? Since that's what's implemented right now. But according to the architecture doc, it seems the formTemplates are camp-specific?

2022-04-16 16:27 UTC, amanda-guo commented on backend/typescript/services/interfaces/adminService.ts
> +   * @returns A WaiverDTO that contains the waiver.
nit: update this @returns to a FormTemplateDTO

2022-04-16 16:27 UTC, amanda-guo commented on backend/typescript/services/interfaces/adminService.ts
> +   * @throws Error if waiver retrieval fails.
nit: update this @throws to be specific to a form template

2022-04-16 16:27 UTC, amanda-guo commented on backend/typescript/services/interfaces/adminService.ts
> +   * @returns A WaiverDTO that contains the waiver.
nit: update this @returns to a FormTemplateDTO

2022-04-16 16:27 UTC, amanda-guo commented on backend/typescript/services/interfaces/adminService.ts
> +   * @throws Error if waiver retrieval fails.
nit: update this @throws to be specific to a form template

2022-04-16 16:29 UTC, amanda-guo commented on backend/typescript/services/implementations/adminService.ts
> +        `Failed to update waiver. Reason: ${getErrorMessage(error)}`,
nit: update error message to be specific to form templates

2022-04-16 16:30 UTC, amanda-guo commented on backend/typescript/services/implementations/adminService.ts
> +      Logger.error(`Failed to get waiver. Reason = ${getErrorMessage(error)}`);
nit: update error message to be specific to form templates

2022-04-16 16:34 UTC, amanda-guo commented on backend/typescript/services/implementations/adminService.ts
> +      console.log(form?.formQuestions);
nit: can remote this console.log

2022-04-16 16:35 UTC, amanda-guo reviewed
another thing - it's mentioned in the notion ticket "Get/edit the questions in the template." Was that also implemented in the scope of this PR?

2022-04-20 23:56 UTC, annechung requested changes
good start! just need to make some fixes to return the full formquestion objects (in both get and update handlers) and to remove waiver things :')

2022-04-20 23:56 UTC, annechung commented on backend/typescript/services/implementations/userService.ts
> +                  camps: (oldUser as CampLeader).campSessions,
think we need to change all the `camps` in this file to `campSessions`  - do you mind making that change for now? @amanda-guo should be updating some of this code in her PR as well

2022-04-20 23:56 UTC, annechung commented on backend/typescript/services/implementations/adminService.ts
> +      form = await formTemplateModel.findOne();
you need to populate the formQuestions here so we return the full formQuestion objects and not just the ids; an example of populating here: https://github.com/uwblueprint/focus-on-nature/blob/main/backend/typescript/services/implementations/camperService.ts#L150

2022-05-14 18:42 UTC, annechung commented on backend/typescript/services/implementations/adminService.ts
> +      /* eslint no-underscore-dangle: 0 */
we should delete the existing form questions before creating new ones

2022-05-14 19:33 UTC, annechung commented on backend/typescript/services/implementations/adminService.ts
> +      await formTemplateModel.remove({});
ah i think we want to delete the questions in the actual formQuestions collection? so old unused questions aren't hanging around. so before creating the new question documents we should delete all current questions in formQuestions

2022-05-18 05:27 UTC, AmandaMisjuwar approved these changes

2022-05-18 05:28 UTC, annechung approved these changes

2022-05-18 05:28 UTC, merged