feat: update camp model to have on object for location
uwblueprint/focus-on-nature pull request #73
Opened 2022-06-22 22:07 UTC by uyousafzai54

## Notion ticket link

[Ticket Name](https://www.notion.so/uwblueprintexecs/Camp-model-update-f04d52deb7774f828c544c660b03a63b)

## Implementation description
```
{
	streetAddress1: string
	streetAddress2: string (optional)
	city: string
	province: string
	postalCode: string
}
```
* Updated the location model to the new schema shown above
* Updated the CampDTO 
* Updated the Camp Validator
* Updated automated tests for creating and updating camps 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-25 19:29 UTC, annechung commented on backend/typescript/middlewares/validators/campValidators.ts
> +    if (!validatePrimitive(body.locaton.streetAddress1, "string")) {
> locaton
bruh

2022-06-25 19:31 UTC, annechung commented on backend/typescript/models/camp.model.ts
> +    postalCode: string;
can you set everything to required except for streetAddress2

2022-06-26 01:43 UTC, uyousafzai54 commented on backend/typescript/middlewares/validators/campValidators.ts
> +    if (!validatePrimitive(body.locaton.streetAddress1, "string")) {
bruh

2022-06-30 01:37 UTC, NirmalHegde commented on backend/typescript/middlewares/validators/campValidators.ts
> +    if (!validatePrimitive(body.locaton.streetAddress1, "string")) {
bruh

2022-07-02 19:32 UTC, annechung requested changes
good start! you should update the camp creation/edit methods to also pass in these new address fields

2022-08-10 03:09 UTC, annechung approved these changes
nice work :)

2022-08-10 03:09 UTC, merged